version: 0.0
os: linux
files:
  # - source: /
  #   destination: /home/ec2-user/workspace/demo_app
  - source: /index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/start.sh
      runas: ec2-user

